# Generated by Django 3.2.7 on 2022-04-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_alter_student_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='technical_skills',
            field=models.CharField(max_length=250),
        ),
    ]
